<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDR8IP0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDR8IP0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDR8IP0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDR8IP0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCDR8IP0\App_KernelDevDebugContainer([
    'container.build_hash' => 'CDR8IP0',
    'container.build_id' => 'd684f246',
    'container.build_time' => 1708187536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDR8IP0');
